paths:
  /users/sign-up:
    post:
      summary: 회원 가입 API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                gender:
                  type: string
                birth:
                  type: string
                  format: date
                address:
                  type: string
                detailAddress:
                  type: string
                phoneNumber:
                  type: string
                preferences:
                  type: array
                  items:
                    type: number
      responses:
        "200":
          description: 회원 가입 성공 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultType:
                    type: string
                    example: SUCCESS
                  error:
                    type: object
                    nullable: true
                    example: null
                  success:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      preferCategory:
                        type: array
                        items:
                          type: string
        "400":
          description: 회원 가입 실패 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultType:
                    type: string
                    example: FAIL
                  error:
                    type: object
                    properties:
                      errorCode:
                        type: string
                        example: U001
                      reason:
                        type: string
                      data:
                        type: object
                  success:
                    type: object
                    nullable: true
                    example: null